his_size: 50  # history
title_size: 30
abstract_size: 50
word_freq_threshold: 1
entity_size: 5

# dim
word_emb_dim: 300
category_emb_dim: 300  #?哪里来的维度啊
subcategory_emb_dim: 300
entity_emb_dim: 100

# For additive attention
attention_hidden_dim: 200
head_num: 20
head_dim: 20
word_filter_num: 0

use_graph: false
use_entity: false
num_neighbors: 10

# long-chain modeling
long_chain_len: 6

gat_heads: 1 # 2?3?4?不造啊

lstm_layers: 1
