# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - default
  - override dataset: MINDlarge
  - override model: GLORY
  - _self_

optimizer:
  lr: 0.0002 

num_epochs: 5
batch_size: 32            # dataloaders'batch_size = batch_size / gpu_num
accumulation_steps: 1   # final acutal batch_size = batch_size * accumulation_steps
gpu_num: 4

# load or not
load_checkpoint: false
load_mark: base_large
train_mode: true
val_mode: true

model:
  use_entity: true
  entity_neighbors: 10
  head_num: 20
  head_dim: 20
  use_graph_type: 0
  directed: true
  num_neighbors: 8
  k_hops: 5
  long_chain_len: 4

logger:
  exp_name: GLORY
  run_name: ${model.model_name}_${dataset.dataset_name}_${model.k_hops}-${model.num_neighbors}-${model.entity_neighbors}

ml_label: default

num_workers: 4
early_stop_patience: 5
reprocess: false
reprocess_neighbors: false
warmup_ratio: 0.1

val_skip_epochs: 1
# 高保真验证设置：不缓存、全量评估（如需提速，可在命令行覆盖）
val_steps: 20000        # 每 2 万步验证一次
val_start_step: 20000   # 从 2 万步后才开始验证
val_embed_mode: recompute   # 每次重编码，保持与当前权重一致
val_sample_ratio: 1.0  # 全量验证
val_amp: false         # 关闭 AMP，使用 FP32 验证
val_use_offline_neighbors: false  # 关闭离线邻居注入，消除与 GLORY 的差异
