# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - default
  - override dataset: MINDsmall
  - override model: GLORY
  - _self_

optimizer:
  lr: 0.0002

num_epochs: 5
batch_size:  32          # dataloaders'batch_size = batch_size / gpu_num
accumulation_steps: 1     # final acutal batch_size = batch_size * accumulation_steps
gpu_num: 1

# load or not
load_checkpoint: false
load_mark: base_small
train_mode: true
val_mode: true

model:
  use_entity: true
  entity_neighbors: 10
  head_num: 20
  head_dim: 20
  use_graph_type: 0
  directed: true
  num_neighbors: 8
  k_hops: 2
  

logger:
  exp_name: GLORY
  run_name: ${model.model_name}_${dataset.dataset_name}_${model.k_hops}-${model.num_neighbors}-${model.entity_neighbors}

ml_label: default

num_workers: 4          #工作线程数
early_stop_patience: 8 #模型的性能在5个连续的周期内都没改进，则训练就会停止
reprocess: False
reprocess_neighbors: false
warmup_ratio: 0.1 #Learning ratio can increase gradually by setting this
log_steps: 1000  #记录每1000个iteration的性能表现

val_skip_epochs: 1
val_steps: 1000  #每1000个iteration进行一次验证
val_start_step: 8000  # 从该步后才进行验证
# 验证新闻编码策略：recompute(每次重编码，保真) | cache(第一次计算后缓存复用)
val_embed_mode: recompute
# 验证采样比例：1.0 为全量，<1.0 可加速（近似指标）
val_sample_ratio: 1.0
# 验证阶段 AMP：为保证数值保真，默认关闭
val_amp: false
# 是否在验证阶段使用离线邻居向量注入（news_outputs_dict/trimmed_neighbors）
val_use_offline_neighbors: false
